version: '3.0'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    container_name: chattydb
    volumes:
      - ./mongodb:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - '6379:6379'
